class ProvinceHelper {
  static List<String> provinceList = [
    'Aceh',
    'Bengkulu',
    'Sumatera Utara',
    'Sumatera Selatan',
    'Sumatera Barat',
    'Bangka Belitung',
    'Riau',
    'Jambi',
    'Lampung',
    'Papua',
    'Kepulauan Riau',
    'Kalimantan Barat',
    'Kalimantan Timur',
    'Kalimantan Selatan',
    'Kalimantan Tengah',
    'Kalimantan Utara',
    'Banten',
    'Jakarta',
    'Bali',
    'Gorontalo',
    'Maluku',
    'NTT',
    'NTB',
    'Jawa Barat',
    'Yogyakarta',
    'Jawa Timur',
    'Sulawesi Barat',
    'Sulawesi Tengah',
    'Sulawesi Utara',
    'Sulawesi Tenggara',
    'Sulawesi Selatan',
    'Maluku Utara',
    'Papua Barat',
  ];
}
